apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager
  labels:
    app: account-manager
spec:
  selector:
    matchLabels:
      app: account-manager
  replicas: 2
  template:
    metadata:
      labels:
        app: account-manager
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: account-manager
          image: local/account-manager:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: prometheus-jmx
              containerPort: 9099
          env:
            - name: JAEGER_SERVICE_NAME
              value: accountmgr
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
            - name: JAEGER_TAGS
              value: "version=${VERSION}"
            - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
              value: "/metrics"