kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-manager
  labels:
    app: order-manager
spec:
  selector:
    matchLabels:
      app: order-manager
  replicas: 3
  template:
    metadata:
      labels:
        app: order-manager
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: order-manager
          image: local/order-manager:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: prometheus-jmx
              containerPort: 9099
          env:
            - name: JAEGER_SERVICE_NAME
              value: ordermgr
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
            - name: JAEGER_TAGS
              value: "version=${VERSION}"
            - name: ACCOUNT_MANAGER_URL
              value: "http://account-manager:8080"
            - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
              value: "/metrics"